### ISSUE TITLE
mediaOptions

### ISSUE THREAD

**Issue by 1390006090** [1249682741/postcss-px-to-viewport-8-media#1]
媒体查询里面的代码不会跟着mediaOptions 的视窗改变  还是原来的

**Comment by the-pikachu-dev** [comment]
要不直接说说你现在的需求？ 我的设想里面都用特意写媒体查询了。那他就不需要转了呀

**Comment by 1390006090** [comment]
postcsspxtoviewport8media({
          unitToConvert: 'px', // 需要转换的单位，默认为"px"
          viewportWidth: 1920, // 设计稿的视口宽度
          mediaQuery: true, // 媒体查询里的单位是否需要转换单位
          unitPrecision: 6, // 单位转换后保留的精度
          mediaOptions: [ //根据媒体查询添加不同的视口宽度
            {
              mediaParam: "screen and (max-width: 1080px)",
              viewportWidth: 1080,
              viewportUnit: "vw"
            },
          ]
        })
        比如这样设置，1080px的时候 视窗就是1080  这没问题
        但是如果在媒体查询写代码 就会按照视窗1920
        不应该统一按照1080么......

**Comment by 1390006090** [comment]
其实我的主要需求是 有个BUG 在vue+vite 项目里面 开启了  landscape  改样式就不会自动刷新了。除非把项目重启

**Comment by the-pikachu-dev** [comment]
> 其实我的主要需求是 有个BUG 在vue+vite 项目里面 开启了 landscape 改样式就不会自动刷新了。除非把项目重启

  要不你开个仓库提供一下示例？ 我本地试了一下没问题啊。

**Comment by 1390006090** [comment]
好等等

**Comment by 1390006090** [comment]
https://gitee.com/yu_kainb/test-adaptation.git
在APP.VUE里面有个边框 你可以在横屏状态下注释一下他试试。麻烦了

**Comment by the-pikachu-dev** [comment]
将插件升级一下版本把。原来这个问题我之前解决过了。但是没发布
`"postcss-px-to-viewport-8-media": "^1.0.1",`

**Comment by the-pikachu-dev** [comment]
想了解详情的话可以看 [commit 89326b](https://github.com/1249682741/postcss-px-to-viewport-8-media/commit/89326bf9fe367a8be28b8c92500864cd92f88903)
